### PR TITLE
test: integration tests for PriceFeedConsumer and Uniswap

### PR DESCRIPTION
**Pull request by enitrat**
Requires a `.env` file with `MAINNET_RPC_URL` address

### CODE REVIEW

**Review by patriciobcs — CHANGES_REQUESTED** [review]
The following test fail on my side (add debug):

```
Encountered 1 failing test in test/integration_tests/ForkTest.t.sol:ForkTest
[FAIL. Reason: AS] testFiftyEthFiftyUSDC() (gas: 287924)

Encountered 2 failing tests in test/unit_tests/Portfolio.t.sol:PortfolioTest
[FAIL. Reason: Assertion failed.] testGetPortfolioValueMultipleTokens() (gas: 435132)
[FAIL. Reason: Assertion failed.] testRebalanceLite() (gas: 413502)
```

It seems assertions are failing.

**Comment by enitrat** [comment]
It's fixed in #17, will rebase after merge

**Comment by patriciobcs** [comment]
> It's fixed in #17, will rebase after merge

What about `testFiftyEthFiftyUSDC`?

**Comment by enitrat** [comment]
It's related to the same rebalance problem

**Comment by enitrat** [comment]
Ready to merge and follow-up with integration on a local mainnet fork

**Review by patriciobcs — APPROVED** [review]

**Pull request merged**
